on:
  push:
    tags:
      - "v*"
  
name: Release Stona

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare Releases
        run: sudo bash ./build/builder.sh
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            stona_all_platforms.zip
            stona_darwin_amd64.zip
            stona_linux_amd64.zip
            stona_linux_arm64.zip
            stona_linux_arm.zip
            stona_win_amd64.zip
            stona_win_arm.zip

            
      
